corr_features_spearman_list:
- sex_ Male
- race_ White
- country_ United-States
- age_ordinal
- marital-status_ Divorced
- workclass_ State-gov
- workclass_ Local-gov
- workclass_ Private
- education_ordinal
- marital-status_ Married-civ-spouse
- country_Other
- occupation_ Adm-clerical
- workclass_ Self-emp-inc
- relationship_ Unmarried
- sex_ Female
- workclass_Other
- relationship_ Own-child
- workclass_ Self-emp-not-inc
- workclass_ Federal-gov
- marital-status_ Never-married
- relationship_ Not-in-family
