corr_features_spearman_list:
- relationship_ Not-in-family
- workclass_ Federal-gov
- workclass_ Private
- workclass_ Self-emp-inc
- sex_ Female
- country_ United-States
- workclass_ Local-gov
- race_ White
- age_ordinal
- workclass_Other
- workclass_ Self-emp-not-inc
- relationship_ Own-child
- workclass_ State-gov
- marital-status_ Divorced
- occupation_ Adm-clerical
- country_Other
- marital-status_ Married-civ-spouse
- relationship_ Unmarried
- sex_ Male
- marital-status_ Never-married
- education_ordinal
