corr_features_spearman_list:
- sex_ Female
- relationship_ Own-child
- marital-status_ Married-civ-spouse
- workclass_ Federal-gov
- workclass_ Private
- education_ordinal
- marital-status_ Never-married
- workclass_Other
- marital-status_ Divorced
- workclass_ State-gov
- workclass_ Self-emp-inc
- sex_ Male
- age_ordinal
- workclass_ Local-gov
- race_ White
- relationship_ Unmarried
- country_Other
- relationship_ Not-in-family
- workclass_ Self-emp-not-inc
- country_ United-States
