corr_features_spearman_list:
- relationship_ Unmarried
- workclass_ Private
- age_ordinal
- country_ United-States
- country_Other
- occupation_ Adm-clerical
- marital-status_ Never-married
- relationship_ Own-child
- workclass_Other
- workclass_ State-gov
- sex_ Male
- marital-status_ Divorced
- workclass_ Local-gov
- workclass_ Federal-gov
- sex_ Female
- relationship_ Not-in-family
- workclass_ Self-emp-inc
- workclass_ Self-emp-not-inc
- race_ White
- marital-status_ Married-civ-spouse
- education_ordinal
