corr_features_spearman_list:
- age_ordinal
- workclass_ Self-emp-inc
- workclass_ Federal-gov
- workclass_ Local-gov
- workclass_ Self-emp-not-inc
- sex_ Male
- country_Other
- race_ White
- country_ United-States
- workclass_ Private
- workclass_ State-gov
- marital-status_ Never-married
- education_ordinal
- relationship_ Unmarried
- relationship_ Not-in-family
- workclass_Other
- relationship_ Own-child
- marital-status_ Married-civ-spouse
- sex_ Female
- occupation_ Adm-clerical
- marital-status_ Divorced
