columns:
  - age: int
  - workclass: category
  - education: category
  - marital-status: category
  - occupation: category
  - relationship: category
  - race: category
  - sex: category
  - capital-gain: int
  - capital-loss: int
  - hours-per-week: int
  - country: category
  - salary: categoty
  

numerical_columns:
  - age
  - capital-gain
  - capital-loss
  - hours-per-week


columns_nan:
  - occupation        
  - workclass         
  - country


correlation_columns:
  - capital-loss
  - capital-gain
  - hours-per-week
  - age
  

categorical_columns:
  - age
  - workclass
  - education
  - marital-status
  - occupation
  - relationship
  - race
  - sex
  - capital-gain
  - capital-loss
  - hours-per-week
  - country

nominal_columns:
  - marital-status
  - relationship
  - race
  - sex
  - country
  - occupation
  - workclass

nominal_one_hot_encoding:  
  - relationship
  - race
  - sex
  - country 
                
nominal_one_hot_encoding_top_x: 
  - marital-status
  - occupation
  - workclass

ordinal_columns:
  - education
  - age
  - hours-per-week
  - capital_gain
  - capital_loss



drop_columns:
  - fnlwgt
  - education-num
# - br_000
# - bq_000


corr_features_spearman_list:
  - occupation_ Protective-serv
  - race_ White
  - workclass_ State-gov
  - education_ordinal
  - marital-status_ Divorced
  - hours-per-week_ordinal
  - age_ordinal
  - country_ United-States
  - relationship_ Wife
  - workclass_Missing
  - workclass_ Federal-gov
  - marital-status_ Never-married
  - occupation_Missing
  - workclass_ Local-gov
  - occupation_ Adm-clerical
  - marital-status_ Married-civ-spouse
  - relationship_ Unmarried
  - country_Rare_var
  - workclass_ Self-emp-inc
  - workclass_ Self-emp-not-inc


relationship:
  - ' Unmarried'
  - ' Husband'
  - ' Not-in-family'
  - ' Own-child'
  - ' Wife'
  - ' Other-relative'

education:
  - ' HS-grad'
  - ' Some-college'
  - ' Assoc-voc'
  - ' 11th'
  - ' 10th'
  - ' Bachelors'
  - ' Assoc-acdm'
  - ' Prof-school'
  - ' 12th'
  - ' Masters'
  - ' 9th'
  - ' 7th-8th'
  - ' Doctorate'
  #- 'Rare-var'
  #- ' 1st-4th'
  #- ' Preschool'
  #- ' 5th-6th'



workclass:
 - ' Private'
 - ' Self-emp-not-inc'
 - ' Local-gov'
 - ' State-gov'
 - ' Self-emp-inc'
 - ' Federal-gov'
 - ' Without-pay'
 - ' Never-worked'

maritalstatus: 
 - ' Never-married'
 - ' Married-civ-spouse'
 - ' Widowed'
 - ' Divorced'
 - ' Separated'
 - ' Married-spouse-absent'
 - ' Married-AF-spouse'


occupation: 
 - ' Other-service'
 - ' Machine-op-inspct'
 - ' Prof-specialty'
 - ' Craft-repair'
 - ' Sales'
 - ' Transport-moving'
 - ' Adm-clerical'
 - ' Handlers-cleaners'
 - ' Exec-managerial'
 - ' Tech-support'
 - ' Protective-serv'
 - ' Farming-fishing'
 - ' Priv-house-serv'
 - ' Armed-Forces'


race: 
 - ' Black'
 - ' White'
 - ' Asian-Pac-Islander'
 - ' Amer-Indian-Eskimo'
 - ' Other'

sex:
 - ' Female'
 - ' Male'



 